-- AlterTable
ALTER TABLE "address" ALTER COLUMN "date_insert" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_update" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "budget" ALTER COLUMN "date_due" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_insert" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_update" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "budget_payment" ALTER COLUMN "date_insert" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_update" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_due" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "budget_service" ALTER COLUMN "date_insert" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_update" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "company" ALTER COLUMN "date_insert" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_update" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "immobile" ALTER COLUMN "date_insert" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_update" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "immobile_owner" ALTER COLUMN "date_insert" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_update" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "immobile_point" ALTER COLUMN "date_insert" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_update" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "login_token" ALTER COLUMN "date_insert" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_update" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "validation_due" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "payment" ALTER COLUMN "date_due" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_insert" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_update" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "person" ALTER COLUMN "date_insert" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_update" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "point" ALTER COLUMN "date_insert" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_update" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "professional" ALTER COLUMN "date_insert" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_update" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "project" ALTER COLUMN "date_due" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_insert" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_update" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "service" ALTER COLUMN "date_due" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_insert" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_update" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "service_immobile" ALTER COLUMN "date_insert" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_update" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "service_stage" ALTER COLUMN "date_insert" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_update" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_due" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "subject_message" ALTER COLUMN "date_insert" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_update" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "telephone" ALTER COLUMN "date_insert" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_update" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "user" ALTER COLUMN "date_insert" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date_update" SET DATA TYPE TIMESTAMP(3);
